USE ecommerce_db;
-- Tabla de Usuarios
CREATE TABLE User (
    id VARCHAR(36) PRIMARY KEY,
    email VARCHAR(191) UNIQUE NOT NULL,
    nombre VARCHAR(191),
    password VARCHAR(191) NOT NULL,
    rol ENUM('CLIENTE', 'ADMINISTRADOR') DEFAULT 'CLIENTE',
    createdAt DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
    updatedAt DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
);
-- Tabla de Productos
CREATE TABLE Product (
    id VARCHAR(36) PRIMARY KEY,
    nombre VARCHAR(191) NOT NULL,
    descripcion TEXT NOT NULL,
    precio DECIMAL(10,2) NOT NULL,
    sku VARCHAR(191) UNIQUE NOT NULL,
    stock INT NOT NULL,
    categoria VARCHAR(191) NOT NULL,
    imagenes TEXT NOT NULL,
    createdAt DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
    updatedAt DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
);
-- Tabla de Pedidos
CREATE TABLE `Order` (
    id VARCHAR(36) PRIMARY KEY,
    usuarioId VARCHAR(36) NOT NULL,
    estado ENUM('PENDIENTE', 'PAGADO', 'ENVIADO', 'ENTREGADO', 'CANCELADO') DEFAULT 'PENDIENTE',
    total DECIMAL(10,2) NOT NULL,
    createdAt DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
    updatedAt DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    FOREIGN KEY (usuarioId) REFERENCES User(id)
);
-- Tabla de Items de Pedido
CREATE TABLE OrderItem (
    id VARCHAR(36) PRIMARY KEY,
    pedidoId VARCHAR(36) NOT NULL,
    productoId VARCHAR(36) NOT NULL,
    cantidad INT NOT NULL,
    precio DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (pedidoId) REFERENCES `Order`(id),
    FOREIGN KEY (productoId) REFERENCES Product(id)
);

